name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
#    - name: Make gradlew executable
#      run: chmod +x ./gradlew
#    - name: Build ktor
#      run: ./gradlew installDist
    - name: Build ktor
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: installDist
        gradle-version: wrapper
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build the Docker image
      run: docker buildx build --platform linux/arm --file Dockerfile --tag maxdroz/test-repo:$(date +%s) --tag maxdroz/test-repo:latest --push .
