name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
#    - name: Make gradlew executable
#      run: chmod +x ./gradlew
#    - name: Build ktor
#      run: ./gradlew installDist
    - name: Build ktor
      uses: burrunan/gradle-cache-action@v1
      with:
        arguments: installDist
        gradle-version: wrapper
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
#    - name: Prepare docker cache
#      uses: satackey/action-docker-layer-caching@v0.0.11
    # Ignore the failure of a step and avoid terminating the job.
#        continue-on-error: true

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: maxdroz/test-repo
        # generate Docker tags based on the following events/attributes
        tags: |
          type=raw,value=latest
          type=schedule,pattern={{date 'X'}}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
#        tags: maxdroz/test-repo:latest,maxdroz/test-repo:$(date +%s)
        tags: ${{ steps.meta.outputs.tags }}
        platforms: linux/arm
        cache-from: type=gha
        cache-to: type=gha,mode=max

#    - name: Build the Docker image
#      run: docker buildx build --platform linux/arm --file Dockerfile --tag maxdroz/test-repo:$(date +%s) --tag maxdroz/test-repo:latest --push .
